ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/step_counter
obj-y := bma4.o bma423.o bma4xy_driver.o
