ccflags-y += -I$(srctree)/drivers/misc/mediatek/C7S
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/step_counter

obj-$(CONFIG_C8_NRF_CONTROL) += nrf.o nrf_acc.o nrf_ebus.o nrf_hrs.o nrf_misc.o nrf_step.o nrf_tilt.o nrf_vibr.o
